# ===========================  build режим  =========================
services:
  database:
    image: postgres:17.2
    container_name: your_photo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: your_photo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: your_photo_backend
    ports:
      - "4200:4200"
    environment:
      DATABASE_URL: "postgresql://postgres:12345@database:5432/your_photo"
      NEXT_PUBLIC_API_URL: "http://localhost:4200"
    depends_on:
      - database
    command: ["node", "dist/main.js"]  # Запуск приложения в продакшн-режиме

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: your_photo_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:4200"  # Изменено на имя сервиса
    command: ["node", ".next/standalone/server.js"]  # Запуск Next.js в продакшн-режиме

volumes:
  postgres_data:

